language: node_js
cache:
  directories:
    - ~/.npm
    - 'node_modules'
notifications:
  email: false
node_js:
  - '9.3.0'
install:
  - 'npm install'
before_script:
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sudo apt-get update
  - sudo apt-get install -y libappindicator1 fonts-liberation
  - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  - sudo dpkg -i google-chrome*.deb
script:
  - 'npm run test -- --watch false -cc'
after_success:
  - npm run build:lib
  - npm run build:app
  - npm run travis-deploy-once "npm run semantic-release"
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
